server:
  port: 8082

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:profile_db}
    username: ${DB_USERNAME:fitnessai}
    password: ${DB_PASSWORD:fitnessai}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
